name:                es-tools
version:             0.1.0.0
license:             BSD3
author:              "David Turner"
maintainer:          "david.turner@elastic.co"
copyright:           "2018 Elastic"

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- conduit
- conduit-extra
- directory
- filepath
- iso8601-time
- process
- stm
- streaming-commons
- time
- resourcet
- text
- unix

executables:
  start-node:
    main:                Main.hs
    source-dirs:         start-node
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
