name:                es-tools
version:             0.1.0.0
license:             BSD3
author:              "David Turner"
maintainer:          "david.turner@elastic.co"
copyright:           "2018 Elastic"

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- bytestring
- conduit
- conduit-extra
- containers
- directory
- filepath
- hashable
- http-client
- http-types
- iso8601-time
- lens
- lens-aeson
- mtl
- process
- random
- resourcet
- stm
- streaming-commons
- text
- time
- unix
- unordered-containers

executables:
  start-node:
    main:                Main.hs
    source-dirs:         start-node
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Werror
